first_value=input('First ')
print('first value is '+first_value)
second_value=input('Second ')
print('second value is '+second_value)
first_float=float(first_value)
second_float=float(second_value)
sum=(first_float+second_float)
print(sum)